//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroCoops.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cooperativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cooperativa()
        {
            this.Entrada = new HashSet<Entrada>();
            this.PedidoEstoque = new HashSet<PedidoEstoque>();
            this.ValorUnitario = new HashSet<ValorUnitario>();
        }
    
        public int IDCooperativa { get; set; }
        public string NomeCooperativa { get; set; }
        public long Telefone { get; set; }
        public string Email { get; set; }
        public long CnpjCooperativo { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Regiao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrada> Entrada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoEstoque> PedidoEstoque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValorUnitario> ValorUnitario { get; set; }
    }
}
