//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroCoops.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgroBDEntities2 : DbContext
    {
        public AgroBDEntities2()
            : base("name=AgroBDEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cooperativa> Cooperativa { get; set; }
        public virtual DbSet<Entrada> Entrada { get; set; }
        public virtual DbSet<Estoque> Estoque { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<PedidoEstoque> PedidoEstoque { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<PessoaFisica> PessoaFisica { get; set; }
        public virtual DbSet<PessoaJuridica> PessoaJuridica { get; set; }
        public virtual DbSet<ProdCoop> ProdCoop { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<Produtor> Produtor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ValorUnitario> ValorUnitario { get; set; }
    }
}
