//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroCoops.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaFisica
    {
        public int IDPessoa { get; set; }
        public long Cpf { get; set; }
        public string Sexo { get; set; }
        public System.DateTime DataNascimento { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Produtor Produtor { get; set; }
    }
}
