//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroCoops.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaJuridica
    {
        public int IDPessoa { get; set; }
        public long Cnpj { get; set; }
        public string NomeFantasia { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
