//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroCoops.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValorUnitario
    {
        public int IDValorUnitario { get; set; }
        public int IDProduto { get; set; }
        public int IDCooperativa { get; set; }
        public System.DateTime DataValorUnitario { get; set; }
        public decimal ValorUnitario1 { get; set; }
    
        public virtual Cooperativa Cooperativa { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
